language: php
dist: xenial
sudo: required

services:
  - docker

php:
  - 7.2
  - 7.3

before_install:
  - cd tests
  - docker-compose up -d
  - cd ..
  - bash ./tests/install-sqlsrv.sh

install:
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - vendor/bin/spiral-cs check src tests

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml

jobs:
  include:
    - stage: Test
      php: 7.4
      before_install:
        - cd tests
        - docker-compose up -d
        - cd ..
      script:
        - vendor/bin/phpunit tests/Database/SQLite
        - vendor/bin/phpunit tests/Database/MySQL
        - vendor/bin/phpunit tests/Database/Postgres

    # Testing various PostgresSQL versions
    - stage: Test
      php: 7.2
      addons:
        postgresql: "9.4"
      env:
        - "DB=postgres POSTGRES=9.4"
      before_install:
        - psql -c 'create database spiral;' -U postgres
      script:
        - vendor/bin/phpunit tests/Database/Postgres

    - stage: Test
      php: 7.2
      addons:
        postgresql: "9.5"
      env:
        - "DB=postgres POSTGRES=9.5"
      before_install:
        - psql -c 'create database spiral;' -U postgres
      script:
        - vendor/bin/phpunit tests/Database/Postgres

    - stage: Test
      php: 7.2
      addons:
        postgresql: "9.6"
      env:
        - "DB=postgres POSTGRES=9.6"
      before_install:
        - psql -c 'create database spiral;' -U postgres
      script:
        - vendor/bin/phpunit tests/Database/Postgres

    - stage: Test
      php: 7.3
      env:
        - "DB=postgres POSTGRES=10.0"
        - PGPORT=5432
      addons:
        postgresql: "10"
        apt:
          packages:
            - postgresql-10
            - postgresql-client-10
      before_install:
        - psql --version
        - psql -c 'create database spiral;' -U postgres
      script:
        - vendor/bin/phpunit tests/Database/Postgres

    - stage: Test
      php: 7.3
      env:
        - "DB=postgres POSTGRES=11.0"
      services:
        - postgresql
      before_install:
        - sudo apt-get update
        - sudo apt-get --yes remove postgresql\*
        - sudo apt-get install -y postgresql-11 postgresql-client-11
        - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
        - sudo service postgresql restart 11
        - psql --version
        - psql -c 'create database spiral;' -U postgres
        - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
      script:
        - vendor/bin/phpunit tests/Database/Postgres

    - stage: Test
      php: 7.3
      env:
        - "DB=postgres POSTGRES=12.0"
      services:
        - postgresql
      before_install:
        - sudo apt-get update
        - sudo apt-get --yes remove postgresql\*
        - sudo apt-get install -y postgresql-12 postgresql-client-12
        - sudo cp /etc/postgresql/{9.6,12}/main/pg_hba.conf
        - sudo service postgresql restart 12
        - psql --version
        - psql -c 'create database spiral;' -U postgres
        - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
      script:
        - vendor/bin/phpunit tests/Database/Postgres

    # MariaDB
    - stage: Test
      php: 7.2
      addons:
        mariadb: "10.2"
      env:
        - "DB=mariadb MARIADB=10.2"
      before_install:
        - mysql -e 'CREATE DATABASE spiral;'
      script:
        - vendor/bin/phpunit tests/Database/MySQL