---

# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# For more information, see:
# https://github.com/actions/labeler/blob/master/README.md

on:  # yamllint disable-line rule:truthy
  pull_request:

name: ğŸ·ï¸ Add labels

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ·ï¸ Apply labels
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

...
